springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true
  show-actuator: false
  writer-with-default-pretty-printer: true

  packages-to-scan:
    - com.truong.corebase.controller

  paths-to-match:
    - /api/**

  cache:
    disabled: true

  default-produces-media-type: application/json
  default-consumes-media-type: application/json

  group-configs:
    - group: "user-api"
      display-name: "User Management APIs"
      paths-to-match: "/api/users/**"
      packages-to-scan: "com.truong.corebase.controller"
    - group: "admin-api"
      display-name: "Admin APIs"
      paths-to-match: "/api/admin/**"
      packages-to-scan: "com.truong.corebase.controller"